###Create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "name": "Sreeja",
  "email": "sreejaguduguntla@gmail.com",
  "dateOfBirth": "12-12-2005",
  "mobileNumber": 8317544742
  
}
###Read all users
GET http://localhost:4000/user-api/users
### Read a user by id
GET http://localhost:4000/user-api/users/69a69427b6d4a28901f27f28
### Delete a user by id
DELETE  http://localhost:4000/user-api/users/69a69427b6d4a28901f27f28

###Activate User
PATCH http://localhost:4000/user-api/users/69a69427b6d4a28901f27f28